import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

/**
 * Helper to add header and footer to PDF pages
 */
const addHeaderFooter = (doc, title = 'QA REPORT') => {
  const totalPages = doc.internal.getNumberOfPages();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);

    // Header
    doc.setFillColor(24, 24, 27); // Dark header bar
    doc.rect(0, 0, pageWidth, 15, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(239, 68, 68); // Red-500
    doc.text('BUG SQUAD', 14, 10);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(244, 244, 245);
    doc.text(title, pageWidth - 14, 10, { align: 'right' });

    // Footer
    doc.setFillColor(24, 24, 27);
    doc.rect(0, pageHeight - 12, pageWidth, 12, 'F');
    doc.setFontSize(8);
    doc.setTextColor(161, 161, 170);
    doc.text('Generated by Bug Squad QA Management System', 14, pageHeight - 4);
    doc.text(`Page ${i} of ${totalPages}`, pageWidth - 14, pageHeight - 4, { align: 'right' });
  }
};

/**
 * Generate & Download Bug Report PDF for a single bug
 */
export const exportBugPDF = async (bug) => {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const bugIdStr = bug.bugId || bug._id || 'BUG-0000';
  let yPos = 24;

  // Document Title Banner
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(239, 68, 68);
  doc.text(`BUG DEFECT REPORT: ${bugIdStr}`, 14, yPos);
  yPos += 8;

  doc.setFontSize(12);
  doc.setTextColor(39, 39, 42);
  doc.text(bug.title || 'Untitled Defect', 14, yPos);
  yPos += 8;

  // Bug Specifications Table
  autoTable(doc, {
    startY: yPos,
    head: [['Field', 'Specification Detail']],
    body: [
      ['Bug ID', bugIdStr],
      ['Project', bug.project?.name || bug.projectName || 'N/A'],
      ['Module', bug.module?.name || bug.moduleName || 'N/A'],
      ['Status', bug.status || 'New'],
      ['Severity', bug.severity || 'Major'],
      ['Priority', bug.priority || 'P3 - Medium'],
      ['Reproducibility', bug.reproducibility || 'Always'],
      ['Reporter', bug.reporter?.name || 'QA Engineer'],
      ['Assigned Developer', bug.assignedTo?.name || 'Unassigned'],
      ['Environment', `${bug.environment || 'QA'} (${bug.browser || 'Chrome'}, ${bug.operatingSystem || 'OS'})`],
      ['Created Date', bug.createdAt ? new Date(bug.createdAt).toLocaleString() : 'N/A'],
    ],
    theme: 'grid',
    headStyles: { fillStyle: 'F', fillColor: [239, 68, 68], textColor: [255, 255, 255], fontStyle: 'bold' },
    styles: { fontSize: 9, cellPadding: 3 },
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 45 } },
  });

  yPos = doc.lastAutoTable.finalY + 8;

  // Description
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(24, 24, 27);
  doc.text('Defect Description:', 14, yPos);
  yPos += 5;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  const descLines = doc.splitTextToSize(bug.description || 'No description provided.', 180);
  doc.text(descLines, 14, yPos);
  yPos += descLines.length * 4.5 + 4;

  // Preconditions & Steps
  if (bug.preconditions) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('Preconditions:', 14, yPos);
    yPos += 5;
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    const preLines = doc.splitTextToSize(bug.preconditions, 180);
    doc.text(preLines, 14, yPos);
    yPos += preLines.length * 4.5 + 4;
  }

  if (bug.stepsToReproduce) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('Steps to Reproduce:', 14, yPos);
    yPos += 5;
    doc.setFontSize(9);
    doc.setFont('courier', 'normal');
    const stepLines = doc.splitTextToSize(bug.stepsToReproduce, 180);
    doc.text(stepLines, 14, yPos);
    yPos += stepLines.length * 4.5 + 4;
    doc.setFont('helvetica', 'normal');
  }

  // Expected vs Actual Result Table
  autoTable(doc, {
    startY: yPos,
    head: [['Expected Result', 'Actual Result Observed']],
    body: [[bug.expectedResult || 'N/A', bug.actualResult || 'N/A']],
    theme: 'grid',
    headStyles: { fillColor: [39, 39, 42], textColor: [255, 255, 255], fontStyle: 'bold' },
    styles: { fontSize: 8.5, cellPadding: 4 },
  });

  yPos = doc.lastAutoTable.finalY + 10;

  addHeaderFooter(doc, `DEFECT TICKET: ${bugIdStr}`);
  doc.save(`${bugIdStr}-Bug-Report.pdf`);
};

/**
 * Generate & Download Project QA Report PDF
 */
export const exportProjectPDF = (project, bugs = [], testCases = []) => {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const projCode = project.projectCode || 'PROJ';
  let yPos = 24;

  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(239, 68, 68);
  doc.text(`PROJECT QA SUMMARY REPORT: ${project.name}`, 14, yPos);
  yPos += 8;

  autoTable(doc, {
    startY: yPos,
    head: [['Project Field', 'Specification']],
    body: [
      ['Project Name', project.name],
      ['Project Code', projCode],
      ['Client', project.client || 'Internal QA'],
      ['Status', project.status || 'Active'],
      ['Project Manager', project.projectManager?.name || 'Unassigned'],
      ['Total Bugs', String(bugs.length)],
      ['Open Bugs', String(bugs.filter((b) => ['New', 'Assigned', 'In Progress', 'Reopened'].includes(b.status)).length)],
      ['Critical Bugs', String(bugs.filter((b) => ['Critical', 'Blocker'].includes(b.severity)).length)],
      ['Total Test Cases', String(testCases.length)],
      ['Passed Test Cases', String(testCases.filter((tc) => tc.status === 'Passed').length)],
    ],
    theme: 'grid',
    headStyles: { fillColor: [239, 68, 68], textColor: [255, 255, 255], fontStyle: 'bold' },
    styles: { fontSize: 9, cellPadding: 3 },
  });

  yPos = doc.lastAutoTable.finalY + 8;

  // Recent Bugs Table
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(24, 24, 27);
  doc.text('Project Defect Overview:', 14, yPos);
  yPos += 4;

  const bugRows = bugs.slice(0, 15).map((b) => [
    b.bugId || b._id,
    b.title || 'Untitled',
    b.severity || 'Major',
    b.priority || 'P3',
    b.status || 'New',
  ]);

  autoTable(doc, {
    startY: yPos,
    head: [['Bug ID', 'Title', 'Severity', 'Priority', 'Status']],
    body: bugRows.length > 0 ? bugRows : [['—', 'No bugs logged for this project', '—', '—', '—']],
    theme: 'striped',
    headStyles: { fillColor: [39, 39, 42], textColor: [255, 255, 255] },
    styles: { fontSize: 8, cellPadding: 2.5 },
  });

  addHeaderFooter(doc, `PROJECT REPORT: ${projCode}`);
  doc.save(`Project-QA-Report-${projCode}.pdf`);
};

/**
 * Generate & Download Active QA Report View PDF
 */
export const exportQAReportPDF = (reportTitle, filterSummary = 'All Data', columns = [], rows = []) => {
  const doc = new jsPDF({
    orientation: 'landscape',
    unit: 'mm',
    format: 'a4',
  });

  let yPos = 24;

  doc.setFontSize(15);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(239, 68, 68);
  doc.text(`QA REPORT: ${reportTitle.toUpperCase()}`, 14, yPos);
  yPos += 6;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(113, 113, 122);
  doc.text(`Applied Filters: ${filterSummary} | Generated: ${new Date().toLocaleString()}`, 14, yPos);
  yPos += 6;

  autoTable(doc, {
    startY: yPos,
    head: [columns],
    body: rows,
    theme: 'grid',
    headStyles: { fillColor: [239, 68, 68], textColor: [255, 255, 255], fontStyle: 'bold' },
    styles: { fontSize: 8, cellPadding: 2.5 },
  });

  addHeaderFooter(doc, reportTitle.toUpperCase());
  doc.save(`QA-Report-${reportTitle.replace(/\s+/g, '-')}.pdf`);
};

/**
 * Generate & Download Requirement Traceability Matrix PDF
 */
export const exportTraceabilityPDF = (matrixRows = [], summary = {}) => {
  const doc = new jsPDF({
    orientation: 'landscape',
    unit: 'mm',
    format: 'a4',
  });

  let yPos = 24;

  doc.setFontSize(15);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(239, 68, 68);
  doc.text('REQUIREMENT TRACEABILITY MATRIX (RTM)', 14, yPos);
  yPos += 6;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(113, 113, 122);
  doc.text(`Total Reqs: ${summary.totalReqs || 0} | Covered: ${summary.coveredReqs || 0} | Coverage: ${summary.coveragePercentage || 0}% | Generated: ${new Date().toLocaleString()}`, 14, yPos);
  yPos += 6;

  const tableRows = matrixRows.map((r) => [
    r.requirementId,
    r.requirementTitle,
    r.testCases.map((tc) => tc.testCaseId).join(', ') || 'None',
    r.testRuns.map((tr) => tr.testRunId).join(', ') || 'None',
    String(r.passedCount),
    String(r.failedCount),
    String(r.blockedCount),
    r.bugs.map((b) => b.bugId).join(', ') || 'None',
    r.isCovered ? 'Covered' : 'Uncovered',
  ]);

  autoTable(doc, {
    startY: yPos,
    head: [['Req ID', 'Requirement Title', 'Test Cases', 'Test Runs', 'Passed', 'Failed', 'Blocked', 'Bugs', 'Coverage']],
    body: tableRows,
    theme: 'grid',
    headStyles: { fillColor: [239, 68, 68], textColor: [255, 255, 255], fontStyle: 'bold' },
    styles: { fontSize: 7.5, cellPadding: 2.5 },
  });

  addHeaderFooter(doc, 'REQUIREMENT TRACEABILITY MATRIX');
  doc.save('Requirement-Traceability-Matrix.pdf');
};

/**
 * Export Analytics Executive PDF Summary
 */
export const exportAnalyticsPDF = (overview, bugData) => {
  const doc = new jsPDF({ orientation: 'p', unit: 'mm', format: 'a4' });
  let yPos = 22;

  doc.setFontSize(15);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(239, 68, 68);
  doc.text('QA ANALYTICS EXECUTIVE REPORT', 14, yPos);
  yPos += 6;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(113, 113, 122);
  doc.text(`Generated on: ${new Date().toLocaleString()}`, 14, yPos);
  yPos += 8;

  const rows = [
    ['Total Projects', String(overview.totalProjects || 0)],
    ['Total Bugs', String(overview.totalBugs || 0)],
    ['Open Bugs', String(overview.openBugs || 0)],
    ['Critical & Blocker Defects', String((overview.criticalBugs || 0) + (overview.blockerBugs || 0))],
    ['Total Test Cases', String(overview.totalTestCases || 0)],
    ['Executed Test Cases', String(overview.executedTestCases || 0)],
    ['Test Pass Rate', `${overview.passRate || 0}%`],
    ['Requirement Coverage', `${overview.reqCoverage || 0}%`],
  ];

  autoTable(doc, {
    startY: yPos,
    head: [['QA Metric Name', 'Value']],
    body: rows,
    theme: 'grid',
    headStyles: { fillColor: [239, 68, 68], textColor: [255, 255, 255], fontStyle: 'bold' },
    styles: { fontSize: 8.5, cellPadding: 3 },
  });

  addHeaderFooter(doc, 'QA ANALYTICS REPORT');
  doc.save('QA-Analytics-Report.pdf');
};
